package com.bottlerocketstudios.compose.repository

import androidx.compose.runtime.mutableStateOf

internal val textString: String = "# These are some examples of commonly ignored file patterns.\n" +
    "# You should customize this list as applicable to your project.\n" +
    "# Learn more about .gitignore:\n" +
    "#     https://www.atlassian.com/git/tutorials/saving-changes/gitignore\n" +
    "\n" +
    "# Node artifact files\n" +
    "node_modules/\n" +
    "dist/\n" +
    "\n" +
    "# Compiled Java class files\n" +
    "*.class\n" +
    "\n" +
    "# Compiled Python bytecode\n" +
    "*.py[cod]\n" +
    "\n" +
    "# Log files\n" +
    "*.log\n" +
    "\n" +
    "# Package files\n" +
    "*.jar\n" +
    "\n" +
    "# Maven\n" +
    "target/\n" +
    "dist/\n" +
    "\n" +
    "# JetBrains IDE\n" +
    ".idea/\n" +
    "\n" +
    "# Unit test reports\n" +
    "TEST*.xml\n" +
    "\n" +
    "# Generated by MacOS\n" +
    ".DS_Store\n" +
    "\n" +
    "# Generated by Windows\n" +
    "Thumbs.db\n" +
    "\n" +
    "# Applications\n" +
    "*.app\n" +
    "*.exe\n" +
    "*.war\n" +
    "\n" +
    "# Large media files\n" +
    "*.mp4\n" +
    "*.tiff\n" +
    "*.avi\n" +
    "*.flv\n" +
    "*.mov\n" +
    "*.wmv\n"


internal val fileBrowserMockData = FileBrowserScreenState(
    path = mutableStateOf(".gitingore"),
    content = mutableStateOf(textString.toByteArray())
)
